%% Import data from text file.
% Script for importing data from the following text file:
%
%    C:\Users\mcaro\Documents\uni\2ano\2 semestre\ATD\HAPT Data Set\our_data\acc_exp11_user06.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2019/03/22 15:24:53

%% Initialize variables.
filename = "HAPT Data Set/RawData/acc_exp20_user10.txt";
delimiter = ' ';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
accexp11user06 = [dataArray{1:end-1}];
plot(accexp11user06);
%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;